### PR TITLE
Added Elasticsearch Dashboards

### PR DESCRIPTION
**Pull request by waliaabhishek**

### CODE REVIEW

**Comment by waliaabhishek** [comment]
@jeanlouisboudart , @OoRobFuoO , @jeqo : Would one of you please be kind enough to sign off this one when you have some time :)

**Review by jeqo — APPROVED** [review]
Beautiful! Adding some screenshots for reference:

Screenshot 2021-08-23 at 22 56 19
Screenshot 2021-08-23 at 22 55 45
Screenshot 2021-08-23 at 22 55 35
Screenshot 2021-08-23 at 22 53 40

The only minor comment would be to align the names to the Grafana dashboards:
- Confluent Schema Registry Overview -> Schema Registry Overview
- KSQLDB Overview -> ksqlDB Overview

**Comment by waliaabhishek** [comment]
Thank you @jeqo for your approval. Good catch with the Dashboard names. Will correct them before merging. Super helpful.

**Comment by OoRobFuoO** [comment]
Overall LGTM for the initial one.
The only feedback I have is the ring widget for the connector is not easy to interpret (3rd diagram shown in @jeqo's screenshot)

I personally would rather have a simple pie chart to show each connector status for simplicity reason.

**Pull request merged**
