### PR TITLE
Adding Metricbeat elastic kibana branch

### PR DESCRIPTION
**Pull request by waliaabhishek**
-- Deleted the old branch and re-adding it with proper git mv statements to carry over history as well as to bump the latest version to 6.1.0-post. All three variants were validated successfully with vanilla 6.1.0-post cp-demo with no issues. 

I have been working on the OpenMetrics based Elastic and Kibana setup that almost replicates the same panels between Grafana and Kibana. This was possible because MetricBeat started supporting the OpenMetrics format.

This will help us get both Grafana & Kibana to almost the same dashboard view. This also removes the dependency for an external component for Jolokia scraper to MetricBeat. Metricbeat is fully owned and created by Elastic and they manage the code. This will help us from a maintainability perspective as well.

To enable sync between both the systems, I have moved the JMX-Exporter YML configuration files from inside the Prometheus stack to shared-assets folder under the main folder. Nothing else was moved. I have tested both the stacks but it would be nice If you could test this before your approval/feedback comments.

### CODE REVIEW

**Comment by waliaabhishek** [comment]
As soon as one of you @jeanlouisboudart , @jeqo can confirm that all is validated, I will merge it to the main 610-post branch. Thank you.

**Review by jeqo — APPROVED** [review]
LGTM, thanks @waliaabhishek !

I like this dashboard at the bottom: 
image

We should replicate it in Grafana.

**Comment by waliaabhishek** [comment]
Granted that one of you have approved and I am eager to update the link as well as get the ELK piece into the main branch. I am going ahead and merging it. 

Thanks to both of you for spending the time to review this major switch ! Much appreciated.

**Comment by waliaabhishek** [comment]
The multi layer pie chart has been there in Kibana since version 2.x
I love the way how it presents the drill downs without actually drilling down.

**Pull request merged**
