### PR TITLE
Adding New Relic example

### PR DESCRIPTION
**Pull request by aschmid13**

### CODE REVIEW

**Comment by waliaabhishek** [comment]
I see a new kafka_broker.yaml file being added. Is there a way to use the existing files in the shared-assets folder for parsing. The current model tries to have a single parsing source if the OpenMetrics format is chosen, for consistency in scraping as well as graphing similarity. 

Can you modify the NR example to use the existing ones ?

**Comment by aschmid13** [comment]
I tried to use the existing kafka_broker.yml file, but New Relic requires metrics to be named a certain way in order to classify the type correctly. For example, this pattern in the new file sends a cumulative counter: ```- pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+), (.+)=(.+)><>Count
  name: kafka_$1_$2_$3_total
  type: COUNTER```

In the old file, this was classified as a gauge so it would show up as very large, always increasing number with no way in New Relic to query the data in a useful way. In the new file, it classifies it as a `counter` and New Relic automatically takes the delta of the counter between values which allows it to be charted properly.

https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration#mapping

FWIW, the file I used is the community example over here: https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-2_0_0.yml

**Review by waliaabhishek — APPROVED** [review]

**Review by albefaedda — APPROVED** [review]

**Comment by hifly81** [comment]
@albefaedda can you solve the conflicts before merging?

**Review by hifly81 — CHANGES_REQUESTED** [review]
pls add only new relic commit

**Comment by albefaedda** [comment]
@aschmid13 could you please create a PR with only the New Relic changes? This one seems to be modifying other dashboards as well. Thanks

**Pull request closed without merging**
