### PR TITLE
#178 integrate confluent cloud cost dashboard - Prom + Grafana

### PR DESCRIPTION
**Pull request by mcolomerc**
- Added CC Billing grafana dashboard. 
- Added CC Billing exporter to Prometheus, this is a custom implementation, based on Prometheus exporters, that gets billing data from CC and transforms responses to Prometheus format.

### CODE REVIEW

**Comment by pneff93** [comment]
I tried it out and paste some screenshots here:
Bildschirmfoto 2024-01-12 um 08 36 21
Bildschirmfoto 2024-01-12 um 08 36 08
Bildschirmfoto 2024-01-12 um 08 35 57

**Review by pneff93 — APPROVED** [review]
LGTM

Comment: the thresholds in the dashboards are hard coded. Any particular reason for the specific thresholds? Especially for connectors and ksqlDB the thresholds are 5, 10, 15. In my case, ksqlDB had 60 $ which is way above the 15

**Comment by hifly81** [comment]
> I tried it out and paste some screenshots here:
> 
> Bildschirmfoto 2024-01-12 um 08 36 08 Bildschirmfoto 2024-01-12 um 08 35 57

@pneff93 @mcolomerc can we link those pics to README?

**Review by hifly81 — CHANGES_REQUESTED** [review]
can we link those pics to README?

**Comment by mcolomerc** [comment]
> LGTM
> 
> Comment: the thresholds in the dashboards are hard coded. Any particular reason for the specific thresholds? Especially for connectors and ksqlDB the thresholds are 5, 10, 15. In my case, ksqlDB had 60 $ which is way above the 15

It is possible to define dynamic thresholds in Grafana?

**Comment by hifly81** [comment]
> > LGTM
> > Comment: the thresholds in the dashboards are hard coded. Any particular reason for the specific thresholds? Especially for connectors and ksqlDB the thresholds are 5, 10, 15. In my case, ksqlDB had 60 $ which is way above the 15
> 
> Is it possible to define dynamic thresholds in Grafana? I added the thresholds to show the options of budget management with Grafana, but I guess it something each user needs to adjust depending on the budget values.

it looks reasonable to me

**Review by hifly81 — APPROVED** [review]

**Pull request merged**
