### PR TITLE
ELK dashboard refresh 

### PR DESCRIPTION
**Pull request by tpham305**
1. Fix start.sh to include docker-compose-override.yaml
2. Modify docker-compose.override.yaml to override elasticsearch and kibana image to 8.3.3 
3. Update ELK Dashboards
- Refresh Kafka dashboard kafka_overview.ndjson
- Refresh Connect dashboard connect_overview.ndjson
- Fix broken queries status in ksqlDB dashboard (ksqldb_overview.ndjson + Mbean changes in shared-assets/jmx-exporter/confluent_ksql.yml)
- Add new dashboard for Producer / Consumer Performance kafka_performance.ndjson

PR-Fix-ksql-querystaus
PR-New-performance-client
PR-Kafka-refresh

### CODE REVIEW

**Review by OoRobFuoO — APPROVED** [review]
Looks good to me

**Comment by OoRobFuoO** [comment]
Please add a README to briefly explain how to use the setup

**Comment by tpham305** [comment]
added README

**Comment by OoRobFuoO** [comment]
Merge

**Pull request merged**
