### PR TITLE
Improvements to Kafka Overview Grafana dashboard

### PR DESCRIPTION
**Pull request by jeqo**
image

Throughput and Thread utilization:
image

Zookeeper and ISR:
image

Changes:
- Health-check: Show controller broker.
- Request rates: Add "All requests" metric, and separate Consumer and Broker fetchs.
- Throughput: Aggregate topics values to show "global" throughput metrics. 
- Thread utilization: invert metric and show "busy time %" instead of idle.
- ZK and ISR: irate metrics, as *_persec metrics return counter and not rate.

### CODE REVIEW

**Comment by waliaabhishek** [comment]
Dont see the Active Controller name when I try to run your updates with cp-demo. Not sure if its my environment or something else.

**Comment by waliaabhishek** [comment]
Can try it again, if you can confirm running it with cp-demo please. Thanks in advance.

**Comment by jeqo** [comment]
@waliaabhishek cp-demo is working now. changing the name of jmx-exporter to align w/cp-ansible was causing the issue. 

Also, updated the dashboard to include a counter of replica leaders per broker:
image

**Comment by jeqo** [comment]
Closing in favor or #44

**Pull request closed without merging**
